---
- name: Mise en place d'une configuration initial pour serveur.
  hosts: selfhost
  vars:
    user: akp

  tasks:
    - name: Installation des applications.
      apt: name={{ item }} update_cache=yes state=latest
      with_items:
        - vim
        - git
        - zsh
        - htop
    - name: Création d'un nouveau utilisateur
      user: name={{ user }} createhome=yes shell=/bin/zsh groups=admin
      
...